apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
  labels:
    app: nginx-app
spec:
  project: default
  source:
    repoURL: https://dbeb93f4d05663a7c6e7f94d6c1f42c0-3000.maxwell.assessments.scaler.com/john_doe/argo-app.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

